### PR TITLE
Add wired-calendar

### PR DESCRIPTION
**Pull request by elingerojo**
fixes: #77 

[Sample wired-calendar](https://elingerojo.github.io/wired-elements/wired-calendar/calendar.html)

I am interested to contribute.
Please try this [demo](https://elingerojo.github.io/wired-elements/wired-calendar/calendar.html) and let me know your comments.
Feedback is appreciated so I can improve the code accordingly.

Cheers!

### CODE REVIEW

**Comment by elingerojo** [comment]
I can PR to a development branch if you prefer.
...or I can create a repository with the `wired-calendar` alone ...and then you clone it so you can add it to your monorepo in you terms.

What will be your preferred workflow for me to contribute?

**Comment by pshihn** [comment]
Thanks! I'll take a look this weekend perhaps. Been swamped with work.

**Comment by hoangph271** [comment]
Why didn't the pointer-cursor used as styling when selecting days...?
Just wondering...! :"}
Excellent job...!

**Comment by elingerojo** [comment]
...just corrected it.
The styling was there but I removed while doing some debugging and forgot to roll it back.
Thanks for noticing it.

**Comment by pshihn** [comment]
Thanks for this merging it in for now. Will include it in the full build when I've played with it a bit more.

**Comment by pshihn** [comment]
@elingerojo I want to refer you in the credits for the calendar contributor. Do you have a Twitter account/anything else you'd like to link?
I'm going to put the Calendar as a beta in the next release.

**Comment by elingerojo** [comment]
> ...a Twitter account/anything else you'd like to link?

No, nothing else to link. Thanks.

> ...as a beta in the next release.

Let me know any related issue with Calendar so I can address it.

**Comment by pshihn** [comment]
No issues yet. I haven't had a chance to play with it much yet, honestly.
I am planning a release in the next few weeks. Will play around and assign you any isses accordingly

**Pull request merged**
